function myFunction()
{
    document.getElementById('demo').innerHTML = "Hello PAKISTAN!";
    document.getElementById('demo').style.color = "crimson";
    window.alert("Alert!\nAre you sure you want to change the 'Tag-Content' and 'Text-Color'.");
}
function myFunction1()
{
    document.getElementById('demo').style.color= "magenta";
}
function myFunction2()
{
    document.getElementById('demo').style.fontSize = "25px";
}
function myFunction3()
{
    document.getElementById('demo').style.display = "none";
}
function myFunction4()
{
    document.getElementById('demo').style.display = "";
}
function myFunction5()
{
    document.write("How are You Doing?");
}
function myFunction6()
{
    window.print();
}